version: "3"
include:
  - ./docker-compose.yaml
services:
  portainer:
    image: portainer/portainer-ce:latest
    #network_mode: host 
    networks:
      - net
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
networks:
  net:
    # Specify driver options
    driver: bridge